CVApp2/Models/City.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CVApp2.Models
{
    public class City : BaseEntity
    {
        [Required,MaxLength(50)]
        public string CityName { get; set; }

        [Required]
        public int RegionId { get; set; }

        public virtual Region Region { get; set; }

       

        public string ZipCode { get; set; }
    }
}

CVApp2/Controllers/CityController.cs
using CVApp2.Models;
using CVApp2.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace CVApp2.Controllers
{
    public class CityController : Controller
    {
          ICityService _cityService;
          IRegionService _regionService;
          IZipCodeService _ZipCodeService;
        public CityController()
        {
            _cityService = new CityService();
            _regionService = new RegionService();
            _ZipCodeService = new ZipCodeService();
        }

        public ActionResult Index()
        {
            return View();
        }

        [OutputCache(Location = OutputCacheLocation.None)] 
        public ActionResult CityDetails(int id)
        {
            var Cities = _regionService.GetCityDetailsByID(id);
            return View("Index");

        }
        // GET: City/Details/5
        public ActionResult Details(int id)
        {
            var Zipcodes = _cityService.GetZipCodeDetailsByCity(id);
            //ViewBag.CityName = _cityService.GetCityByID(id);
           
            City city = new City();
            city = _cityService.GetCityByID(id);

            ViewBag.City = city;

            return View(Zipcodes);
        }

        // GET: City/Create
        public ActionResult Create(int regionId)
        {
            City city = new City { RegionId = regionId }; 

            return PartialView("AddEditPartial", city);
        }

        // POST: City/Create
        [HttpPost]
        public ActionResult Create(City city)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _cityService.AddNew(city);

                    return Content("Success");
                }

                this.Response.StatusCode = 400;
                ModelState.AddModelError("", "Ret venligst følgende fejl:");

                return PartialView("AddEditPartial", city);


            }
            catch (Exception ex)
            {
                this.Response.StatusCode = 400;
               
                ModelState.AddModelError("", ex.Message);

                return PartialView("AddEditPartial", city);
            }
        }

        // GET: City/Edit/5
        public ActionResult Edit(int id)
        {
            City city = _cityService.GetCityByID(id);

            return PartialView("AddEditPartial", city);
        }

        // POST: City/Edit/5
        [HttpPost]
        public ActionResult Edit(City city)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _cityService.Update(city);

                    return RedirectToAction("Details", "Region", new { id = city.RegionId });
                }

                this.Response.StatusCode = 400;
                ModelState.AddModelError("", "Please correct following errors:");

                return PartialView("AddEditPartial", city);
            }
            catch (Exception ex)
            {
                this.Response.StatusCode = 400;
                ModelState.AddModelError("", "korrigere venligst følgende");

                return PartialView("AddEditPartial", city);
            }
         
        }

        // GET: City/Delete/5
        public ActionResult Delete(int id)
        {
            var city = _cityService.GetCityByID(id);

            return PartialView(city);
        }

        // POST: City/Delete/5
        [HttpPost]
        public ActionResult Delete(City city, FormCollection collection)
        {
            try
            {
                _cityService.Delete(city);
                return Content("Deleted");
            }
            catch (Exception ex)
            {
                this.Response.StatusCode = 400;
                ModelState.AddModelError("", ex.Message);
                return PartialView(city);
            }
        }
    }
}

CVApp2/Views/City/AddEditPartial.cshtml
@model CVApp2.Models.City

<div  class="container">

    @using (Ajax.BeginForm(new AjaxOptions { OnSuccess = "handleSuccessCity", OnFailure = "handleError" }))
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <h4>by</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            @Html.HiddenFor(model => model.RegionId, new { htmlAttributes = new { @class = "form-control" } })



            <div class="form-group">
                @Html.Label("by", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.CityName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CityName, "", new { @class = "text-danger" })
                </div>
            </div>


            <hr />

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button value="Save" class="btn btn-primary"><span class="glyphicon glyphicon-save"></span> Gem </button>
                    <input type="button" value="Luk" class="btn btn-default" id="diagCloseBtn" onclick="closeDialog();" />
                </div>
            </div>
        </div>
    }


</div>

CVApp2/Views/City/Delete.cshtml
@model CVApp2.Models.City

<div>
    @using (Ajax.BeginForm(new AjaxOptions { OnSuccess = "handleSuccessCity", OnFailure = "handleError" }))
    {
        @Html.AntiForgeryToken()
        <div class="">

            @Html.HiddenFor(model => model.Id)

            @Html.HiddenFor(model => model.CityName)
            <div class="form-group">
                <div class="col-md-1">
                    <span style="font-size:32px;" class="text-danger glyphicon  glyphicon-question-sign"></span>
                </div>
                <div class="col-md-11">
                    <h4>Er du sikker på du vil slette      ? </h4>
                    <label> @Html.ValueFor(model => model.CityName)?</label>
                    <br />

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <br />
                </div>
            </div>





            <div class="">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" value="Delete" class="btn btn-primary "><span class="glyphicon glyphicon-ok"></span> Ja </button>
                    <input type="button" value="Nej" class="btn btn-default" id="diagCloseBtn" onclick="closeDialog();" />
                </div>
            </div>
        </div>
    }
</div>

CVApp2/Views/City/Details.cshtml
@model IEnumerable<CVApp2.Models.ZipCode>

@{ CVApp2.Models.City city  = new CVApp2.Models.City();}

<div id="ZipCodeContainer" class="container-fluid editContainerPanel restrictedHeight">

    <div class="row">

        <div class="col-md-12">
            

                @if (ViewBag.City != null)
                {
                    
                    city = ViewBag.City;
                    <text>  
                        <h3 style="padding-left:15px;">  Område : @city.Region.RegionName </h3>
                        <hr />
                        <h4 style ="padding-left:15px;"> by : @city.CityName</h4>
                 
                    </text>
                    
                }

            <hr />
        </div>
    </div>

    <div class="row">
        <div class="col-sm-6 col-md-6">


            <div class="EditPageSection bg-primary clearfix">
                <span class="glyphicon glyphicon-map-marker"></span>  post nummer

                @Ajax.ActionLink("Tilføj", "Create", "ZipCode", new { cityId = city.Id }, new AjaxOptions { UpdateTargetId = "ajaxDialog", InsertionMode = InsertionMode.Replace, HttpMethod = "Get", OnSuccess = "showDialog" }, new { @class = "btn btn-xs btn-success pull-right " })

            </div>



            <table class="table table-hover">


                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ZipCodeNumber)

                        </td>
                        <td style="text-align:right; padding-right:15px;">
                            @Ajax.ActionLink("Rediger", "Edit", "ZipCode", new { id = item.Id }, new AjaxOptions { UpdateTargetId = "ajaxDialog", InsertionMode = InsertionMode.Replace, HttpMethod = "Get", OnSuccess = "showDialog" }, new { @class = "btn btn-default btn-sm" })


                            @Ajax.ActionLink("Slet", "Delete", "ZipCode", new { id = item.Id }, new AjaxOptions { UpdateTargetId = "ajaxDialog", InsertionMode = InsertionMode.Replace, HttpMethod = "Get", OnSuccess = "showDialog" }, new { @class = "btn btn-default btn-sm" })
                        </td>
                    </tr>
                }

            </table>
            <br />
            <hr />
            <a href="@Url.Action("Details", "Region", new { id = city.RegionId })" class="btn btn-default"> <span class="glyphicon glyphicon-triangle-left"></span>  Gå tilbage</a> 
        </div>
    </div>
</div>

<div id="ajaxDialog" class="ajaxDialog" style="min-width:500px;"></div>


@section scripts {

    <script>

        $("#ajaxDialog").dialog({ autoOpen: false, modal: true, closeText: "", hide: "fadeOut", title: "post nummer", width: "auto", position: { my: "center top", at: "center top+175", collision: "fit" } });

        function showDialog(data) {
            $("#ajaxDialog").dialog("open");

        };

        function closeDialog() {
            $("#ajaxDialog").dialog("close");
        };

        function handleSuccessZipCode(data) {

            $("#ajaxDialog").dialog("close");
            location.href = "@Url.Action("Details","City", new {id= city.Id } )";
        };

        function handleError(ajaxContext) {

            $("#ajaxDialog").html(ajaxContext.responseText);
        };

    </script>
}

CVApp2/Views/City/Index.cshtml
@model IEnumerable<CVApp2.Models.City>

<div class="container-fluid editcontainerpanel">

    <div class="row">

        <div class="col-md-12">
            <h3 style="padding-left:15px;">

                @if (ViewBag.RegionName != null)
                {
                    CVApp2.Models.Region RegionName = ViewBag.RegionName;
                    <text> @RegionName.RegionName </text>

                }

            </h3>

            <hr />
        </div>
    </div>

    <div class="row">
        <div class="col-sm-4 col-md-4">
            <div id="CityContainer">

                @Ajax.ActionLink("Add", "Create", "City", new { }, new AjaxOptions { UpdateTargetId = "ajaxDialog", InsertionMode = InsertionMode.Replace, HttpMethod = "Get", OnSuccess = "showDialog" }, new { @class = "btn btn-xs btn-success pull-right " })

                <table class="table">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.CityName)
                        </th>
                        <th>
                        </th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.CityName)

                            </td>
                            <td style="text-align:right; padding-right:15px;">
                                @Ajax.ActionLink("Edit", "Edit", "City", new { id = item.Id }, new AjaxOptions { UpdateTargetId = "ajaxDialog", InsertionMode = InsertionMode.Replace, HttpMethod = "Get", OnSuccess = "showDialog" }, new { @class = "btn btn-default btn-sm" })

                                @Html.ActionLink("Details", "Details", "City", new { id = item.Id }, new { @class = "btn btn-default btn-sm" })

                                @Ajax.ActionLink("Delete", "Delete", "City", new { id = item.Id }, new AjaxOptions { UpdateTargetId = "ajaxDialog", InsertionMode = InsertionMode.Replace, HttpMethod = "Get", OnSuccess = "handleSuccessCity" }, new { @class = "btn btn-default btn-sm" })
                            </td>
                        </tr>
                    }

                </table>
            </div>
        </div>
    </div>
</div>