CVApp2/Models/ProfessionTag.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CVApp2.Models
{
    public class ProfessionTag : BaseEntity
    {
        [Required]
        public string Tag { get; set; }
    }
}

CVApp2/Controllers/ProfessionTagsController.cs
using CVApp2.Data;
using CVApp2.Models;
using CVApp2.Services;
using CVApp2.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CVApp2.Controllers
{
    public class ProfessionTagsController : Controller
    {
        // GET: ProfessionTags

        IProfessionTagService _professionTagsService;

        public ProfessionTagsController()
        {
            _professionTagsService = new ProfessionTagService();
        }
        public ActionResult Index()
        {
            var professionTag = _professionTagsService.GetAllTags();

            return View(professionTag);
        }

        // GET: ProfessionTags/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ProfessionTags/Create
        public ActionResult Create()
        {
            ProfessionTag professionTag = new ProfessionTag();

            return PartialView("AddEditPartialTag", professionTag);
        }

        // POST: ProfessionTags/Create
        [HttpPost]
        public ActionResult Create(ProfessionTag professionTag)
        {
             try
            {
                if (ModelState.IsValid)
                {
                    _professionTagsService.AddNew(professionTag);

                    return RedirectToAction("Index");
                }

                this.Response.StatusCode = 400;
                ModelState.AddModelError("", "Please correct following errors:");
                return PartialView("AddEditPartialTag", professionTag);

              
            }
            catch (Exception ex)
            {
                this.Response.StatusCode = 400;
                ModelState.AddModelError("", ex.Message);

                return PartialView("AddEditPartialTag", professionTag);
            }
        }

        // GET: ProfessionTags/Edit/5
        public ActionResult Edit(int id)
        {
            ProfessionTag professionTag = _professionTagsService.GetProfessionTagByID(id);

            return PartialView("AddEditPartialTag", professionTag);
        }

        // POST: ProfessionTags/Edit/5
        [HttpPost]
        public ActionResult Edit(ProfessionTag professionTag)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _professionTagsService.Update(professionTag);

                    return RedirectToAction("Index");
                }

                this.Response.StatusCode = 400;
                ModelState.AddModelError("", "Please correct following errors:");

                return PartialView("AddEditPartialTag", professionTag);
            }
            catch (Exception ex)
            {
                this.Response.StatusCode = 400;
                ModelState.AddModelError("", "korrigere venligst følgende");

                return PartialView("AddEditPartialTag", professionTag);
            }
        }

        // GET: ProfessionTags/Delete/5
        public ActionResult Delete(int id)
        { 
            var professionTag= _professionTagsService.GetProfessionTagByID(id);

            return PartialView(professionTag);
        }

        // POST: ProfessionTags/Delete/5
        [HttpPost]
        public ActionResult Delete(ProfessionTag professionTag, FormCollection collection)
        {
            try
            {
                _professionTagsService.Delete(professionTag);
                return Content("Deleted");
            }
            catch (Exception ex)
            {
                this.Response.StatusCode = 400;
                ModelState.AddModelError("", ex.Message);
                return PartialView(professionTag);
            }
        }
    }
}

CVApp2/Views/ProfessionTags/AddEditPartialTag.cshtml
@model CVApp2.Models.ProfessionTag

<div class="container">

  @using (Ajax.BeginForm(new AjaxOptions { OnSuccess = "handleSuccessErthverv", OnFailure = "handleError" }))
  {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Rolletype</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.Label("Rolletype", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Tag, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Tag, "", new { @class = "text-danger" })
                </div>
            </div>

            <hr />

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button value="Save" class="btn btn-primary"><span class="glyphicon glyphicon-save"></span> Gem </button>
                    <input type="button" value="Luk" class="btn btn-default" id="diagCloseBtn" onclick="closeDialog();" />
                </div>
            </div>
        </div>
    }

</div>


  

CVApp2/Views/ProfessionTags/Delete.cshtml
@model CVApp2.Models.ProfessionTag

<div>
    @using (Ajax.BeginForm(new AjaxOptions { OnSuccess = "handleSuccessErthverv", OnFailure = "handleError" }))
    {
        @Html.AntiForgeryToken()
        <div class="">

            @Html.HiddenFor(model => model.Id)

            @Html.HiddenFor(model => model.Tag)
            <div class="form-group">
                <div class="col-md-1">
                    <span style="font-size:32px;" class="text-danger glyphicon  glyphicon-question-sign"></span>
                </div>
                <div class="col-md-11">
                    <h4>Er du sikker på du vil slette      ? </h4>
                    <label> @Html.ValueFor(model => model.Tag)</label>
                    <br />

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <br />
                </div>
            </div>





            <div class="">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" value="Delete" class="btn btn-primary "><span class="glyphicon glyphicon-ok"></span> Ja </button>
                    <input type="button" value="Nej" class="btn btn-default" id="diagCloseBtn" onclick="closeDialog();" />
                </div>
            </div>
        </div>
    }
</div>

CVApp2/Views/ProfessionTags/Index.cshtml
@model IEnumerable<CVApp2.Models.ProfessionTag>

@{
    ViewBag.Title = "Index";
}

 @section scripts {

    <script>

        $("#ajaxDialog").dialog({ autoOpen: false, modal: true, closeText: "", hide: "fadeOut", title: "Rolletype", width: "auto", position: { my: "center top", at: "center top+175", collision: "fit" } });

        function showDialog(data) {
            $("#ajaxDialog").dialog("open");

        };

        function closeDialog() {
            $("#ajaxDialog").dialog("close");
        };

        function handleSuccessErthverv(data) {
            $("#ajaxDialog").dialog("close");
            location.href = "@Url.Action("Index","ProfessionTags")";

        };

        function handleError(ajaxContext) {

            $("#ajaxDialog").html(ajaxContext.responseText);
        };

    </script>
}

<div id="ErthvervContainer" class="container-fluid editContainerPanel">
    <div class="row">
        <div class="col-md-12">
            <h3 style="padding-left:15px;"> Rolletype</h3>

            <hr />
        </div>
    </div>

    <div class="row">
        <div class="col-sm-6 col-md-6">

            <div class="EditPageSection bg-primary clearfix">
                <span class="glyphicon glyphicon-user"></span>  Rolletype

                @Ajax.ActionLink("Tilføj", "Create", new { }, new AjaxOptions { UpdateTargetId = "ajaxDialog", InsertionMode = InsertionMode.Replace, HttpMethod = "Get", OnSuccess = "showDialog" }, new { @class = "btn btn-xs btn-success pull-right " })

            </div>

            <table class="table table-hover">

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Tag)
                        </td>
                        <td style="text-align:right; padding-right:15px;">
                            @Ajax.ActionLink("Rediger", "Edit", new { id = item.Id }, new AjaxOptions { UpdateTargetId = "ajaxDialog", InsertionMode = InsertionMode.Replace, HttpMethod = "Get", OnSuccess = "showDialog" }, new { @class = "btn btn-default btn-sm" })
                            @Ajax.ActionLink("Slet", "Delete", new { id = item.Id }, new AjaxOptions { UpdateTargetId = "ajaxDialog", InsertionMode = InsertionMode.Replace, HttpMethod = "Get", OnSuccess = "showDialog" }, new { @class = "btn btn-default btn-sm" })
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
</div>

<div id="ajaxDialog" class="ajaxDialog" style="min-width:500px;"></div>