CVApp2/Models/Document.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CVApp2.Models
{
    public class Document : BaseEntity
    {
        [MaxLength(255)]
        public string FileName { get; set; }  //just stores users filename, physically file will be stored with different name for security reasons

        [Required(ErrorMessage = "Vælg dokument gruppe")]
        [Range(1, int.MaxValue, ErrorMessage = "Vælg dokument gruppe")]
        public int DocumentGroupId { get; set; }



        public string JNo { get; set; }

        [DisplayFormat(NullDisplayText = "", DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? JDate { get; set; }


        public string ReleasedForPublication { get; set; } //either date or comment



        public string KarnovNo { get; set; }

        [DisplayFormat(NullDisplayText = "", DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        public DateTime? KarnovDate { get; set; }


        public string TBBNo { get; set; }

        [DisplayFormat(NullDisplayText="",DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        public DateTime? TBBDate { get; set; }


        public string ArbitrationCourtComposition { get; set; }


        [Column(TypeName = "varchar(MAX)")]
        public string Summary { get; set; }


        [Column(TypeName = "varchar(MAX)")]
        public string Tags { get; set; }


        public string Comments { get; set; }


        
        // our internal purpose fields

        [Column(TypeName = "varchar(MAX)")]
        [AllowHtml]
        public string FileContent { get; set; } //for pdf and doc files, text will be extracted and saved for quick search

        [MaxLength(255)]
        public string ServerFileName { get; set; }


        public DateTime? Created { get; set; }

        




       

        public virtual DocumentGroup DocumentGroup { get; set; }
    }
}

CVApp2/Controllers/DocumentController.cs
using CVApp2.Models;
using CVApp2.Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Mime;
using System.Web;
using System.Web.Mvc;
using System.Web.Hosting;

namespace CVApp2.Controllers
{
    public class DocumentController : Controller
    {
        private const string PICTURE_PATH = "~/DocumentFiles/";
        IDocumentService _documentService;

        public DocumentController()
        {
            _documentService = new DocumentService();
        }

        // GET: Document



        public ActionResult ShowDocument(int id, string file)
        {
            Document document = _documentService.GetDocumentById(id);

            if (document == null || document.ServerFileName != file)
                return Content("Invalid Request");

            var cd = new System.Net.Mime.ContentDisposition
            {
                // for example foo.bak
                FileName = document.FileName,

                Inline = true,
            };
            Response.AppendHeader("Content-Disposition", cd.ToString());
            return File(Path.Combine("~/DocumentFiles/", document.ServerFileName), MimeMapping.GetMimeMapping(document.FileName));
        }

        public ActionResult Copypath(int id, string file)
        {
            Document document = _documentService.GetDocumentById(id);

            if (file!="")            
            {


                string pcname = Environment.MachineName;


                string fname = document.ServerFileName;
                string localpath = Path.Combine(PICTURE_PATH, fname);

                string filenames = "\\\\" + pcname + "\\CVApp2\\DocumentFiles\\" + fname + "";
                //DirectoryInfo dirInfo = new DirectoryInfo(HostingEnvironment.MapPath("~/DocumentFiles"));

                //string fullPath = Request.MapPath(localpath);
                //string fulllocalPath = dirInfo.FullName + @"\" + fname;

                FileInfo Fname = new FileInfo(filenames);
                if (Fname.Exists)
                {
                    string clientMachineName = (System.Net.Dns.GetHostEntry(Request.ServerVariables["remote_addr"]).HostName);

                    Clip.MyService myservice = new Clip.MyService();
                    string NewFileName = myservice.SendKnowledgePath(filenames, clientMachineName);
                    return Json(new { NewFileName = NewFileName });



                }
                else
                {
                    return Json(new { NewFileName = "" });
                }
            }
            else
            {
                return Json(new { NewFileName = "" });
            }


        }


        [HttpPost]
        public ActionResult Index(string groupIds, string keywords, int pageIndex, int pageSize)
        {
            int pageCount = 1;

            var documentList = _documentService.GetFiltered(groupIds, keywords, pageIndex, pageSize, out pageCount).OrderByDescending(d => d.Created);

            var docs = documentList.Select(x => new
            {
                x.Id,
                Created = x.Created.Value.ToString("dd/MM/yy"),
                x.DocumentGroup,
                x.DocumentGroupId,
                x.FileName,
                x.ServerFileName,
                x.Tags
            });

            return Json(new { pageCount = pageCount, documents = docs });
        }


        // GET: Document/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Document/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Document/Create
        [HttpPost]
        public ActionResult Create(Document document, HttpPostedFileBase FileName)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    string documentsFolderPath = @"..\DocumentFiles";
                    string documentsFolderPathOnServer = Server.MapPath(documentsFolderPath);
                    if (!Directory.Exists(documentsFolderPathOnServer))
                    {
                        Directory.CreateDirectory(documentsFolderPathOnServer);
                    }
                    if (FileName.ContentLength > 0)
                    {
                        var guid = Guid.NewGuid();
                        var extention = Path.GetExtension(FileName.FileName);
                        var fileName = guid.ToString() + extention;
                        document.ServerFileName = guid.ToString() + extention;
                        var path = Path.Combine(documentsFolderPathOnServer, fileName);
                        FileName.SaveAs(path);
                        document.Created = System.DateTime.Now;
                        document.FileContent = CandidateFilesController.ReadFileData(path).Replace("'", "''");
                        document.FileName = Path.GetFileName(FileName.FileName);
                        _documentService.AddNew(document);
                        return RedirectToAction("Index", "Knowledge", new { selectedGroup = document.DocumentGroupId });
                    }
                    this.Response.StatusCode = 400;
                    ModelState.AddModelError("", "Invalid or empty file selected, please correct it");
                    return View(document);

                }
                else
                {
                    return View(document);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(document);
            }
        }

        // GET: Document/Edit/5
        public ActionResult Edit(int id)
        {
            Document document = _documentService.GetDocumentById(id);
            return View(document);
        }

        // POST: Document/Edit/5
        [HttpPost]
        public ActionResult Edit(Document document, HttpPostedFileBase FileName)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string documentsFolderPath = @"~\DocumentFiles";
                    string documentsFolderPathOnServer = Server.MapPath(documentsFolderPath);
                    if (!Directory.Exists(documentsFolderPathOnServer))
                    {
                        Directory.CreateDirectory(documentsFolderPathOnServer);
                    }
                    if (FileName != null)
                    {
                        if (System.IO.File.Exists(documentsFolderPathOnServer + "\\" + document.ServerFileName))
                        {
                            System.IO.File.Delete(documentsFolderPathOnServer + "\\" + document.ServerFileName);
                        }
                        if (FileName.ContentLength > 0)
                        {
                            var guid = Guid.NewGuid();
                            var extention = Path.GetExtension(FileName.FileName);
                            var fileName = guid.ToString() + extention;
                            document.ServerFileName = guid.ToString() + extention;
                            var path = Path.Combine(documentsFolderPathOnServer, fileName);
                            FileName.SaveAs(path);
                            document.Created = System.DateTime.Now;
                            document.FileContent = CandidateFilesController.ReadFileData(path).Replace("'", "''");
                            document.FileName = Path.GetFileName(FileName.FileName);
                        }
                    }

                    _documentService.Update(document);
                    return RedirectToAction("Index", "Knowledge", new { selectedGroup = document.DocumentGroupId });


                }

                this.Response.StatusCode = 400;
                ModelState.AddModelError("", "Please correct following errors:");

                return View(document);
            }
            catch (Exception ex)
            {
                this.Response.StatusCode = 400;
                ModelState.AddModelError("", "korrigere venligst følgende");

                return View(document);
            }
        }

        // GET: Document/Delete/5
        public ActionResult Delete(int id)
        {

            Document document = _documentService.GetDocumentById(id);
            return PartialView("Delete", document);
        }

        // POST: Document/Delete/5
        [HttpPost]
        public ActionResult Delete(Document document)
        {
            try
            {
                // TODO: Add delete logic here
                string documentsFolderPath = @"~\DocumentFiles";
                string documentsFolderPathOnServer = Server.MapPath(documentsFolderPath);
                _documentService.Delete(document);
                if (System.IO.File.Exists(documentsFolderPathOnServer + "\\" + document.ServerFileName))
                {
                    System.IO.File.Delete(documentsFolderPathOnServer + "\\" + document.ServerFileName);
                }
                return Content("Success");
            }
            catch
            {
                return View(document);
            }
        }

    }
}

CVApp2/Views/Document/Create.cshtml
@model CVApp2.Models.Document

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_KnowledgeLayout.cshtml";

}
<form action="" method="post" enctype="multipart/form-data">
    <div class="editContainerPanel restrictedHeight">
        <div style="padding-bottom:100px;">
            <h3><span class="glyphicon glyphicon-plus"></span> Dokument</h3>
            <hr />
            <div class="row">
                <div class="col-md-5 col-md-offset-1">


                    @using (Html.BeginForm())
                {
                        @Html.AntiForgeryToken()


                        <div class="EditPageSection bg-success">Dokument Detaljer</div>

                        <div class="form-horizontal">

                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            @Html.HiddenFor(model => model.DocumentGroupId, new { id = "documentGroupId" })

                            <div class="form-group">
                                @Html.Label("Dokument Gruppe", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    <div class="form-control" style="height:auto;">
                                        @Html.Action("GroupTree", "DocumentGroup")
                                        @Html.ValidationMessageFor(model => model.DocumentGroupId, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>


                            <div class="form-group">
                                @Html.Label("Vælg Dokument", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    <input type='file' id="file" name="FileName" class="form-control" required>
                                </div>
                            </div>

                            <hr />

                            <div class="form-group">
                                @Html.Label("JNr", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-5">
                                    @Html.EditorFor(model => model.JNo, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.JNo, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.Label("Dato", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.JDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                                    @Html.ValidationMessageFor(model => model.JDate, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <hr />


                            <div class="form-group">
                                @Html.Label("Sendt til offentliggørelse", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.ReleasedForPublication, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ReleasedForPublication, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <hr />

                            <div class="form-group">
                                @Html.Label("Karnov nr", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.KarnovNo, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.KarnovNo, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.Label("Off Karnov dato", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.KarnovDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                                    @Html.ValidationMessageFor(model => model.KarnovDate, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <hr />

                            <div class="form-group">
                                @Html.Label("TBB nr", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.TBBNo, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.TBBNo, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.Label("Off.TBB dato", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.TBBDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                                    @Html.ValidationMessageFor(model => model.TBBDate, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <hr />

                            <div class="form-group">
                                @Html.Label("Voldgiftsrettens sammensætning", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextAreaFor(model => model.ArbitrationCourtComposition, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.ArbitrationCourtComposition, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.Label("Resume", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextAreaFor(model => model.Summary, new { @class = "form-control", @rows = 5})
                                    @Html.ValidationMessageFor(model => model.Summary, "", new { @class = "text-danger" })
                                </div>
                            </div>


                            <div class="form-group">
                                @Html.Label("Bemærkninger", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextAreaFor(model => model.Comments, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <hr />

                            <div class="form-group">
                                @Html.Label("Tag", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextAreaFor(model => model.Tags, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Tags, "", new { @class = "text-danger" })
                                </div>
                            </div>



                            <hr />

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Gem" class="btn btn-success" />
                                </div>
                            </div>

                        </div>
                }



                </div>
            </div>

        </div>

    </div>
</form>
@section scripts{
    <script>
        $(function () {
            $("#groupTree").jstree({
                "checkbox": { "three_state": false },
                "core": {
                    "multiple": false,
                    "themes": {
                        "variant": "large"
                    }
                },
                "plugins": ["wholerow", "checkbox"]
            })
            .on("changed.jstree",
     function (evt, data) {

         var i, j;
         $("#documentGroupId").val(0);
         for (i = 0, j = data.selected.length; i < j; i++) {
             var node_id = (data.instance.get_node(data.selected[i]).id);
             $("#documentGroupId").val(($("#" + node_id).attr("data-value")));

         }
     }
);
            $('.datepicker').datepicker( {dateFormat: 'mm/dd/yy' } );

        })
    </script>
}

CVApp2/Views/Document/Delete.cshtml
@model CVApp2.Models.Document

@{
    ViewBag.Title = "Delete";
}
<div >

    @using (Ajax.BeginForm(new AjaxOptions { OnSuccess = "handleDeleteSuccess", OnFailure = "handleError" }))
    {
        @Html.AntiForgeryToken()

        <div class="">
            
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            @Html.HiddenFor(model => model.DocumentGroupId)
            @Html.HiddenFor(model => model.ServerFileName)
            @Html.HiddenFor(model => model.FileName)

            <div class="form-group">
                <div class="col-md-1">
                    <span style="font-size:32px;" class="text-danger glyphicon  glyphicon-question-sign"></span> 
                </div>
                <div class="col-md-11">
                    <h4  >Er du sikker på du vil slette dokumentet ? </h4>
                    <p style="font-size:larger;"  > @Html.ValueFor(model => model.FileName)</p>
                    <br /><br />
                </div>
            </div>

            

            <div class="">
                <div class="col-md-offset-2 col-md-10">
                    <button value="Delete" class="btn btn-primary "><span class="glyphicon glyphicon-ok"></span> Ja </button>
                    <input type="button" value="Nej" class="btn btn-default"  id="diagCloseBtn" onclick="closeDialog();" />
                   
                </div>
            </div>
            
        </div>
    }
</div>

CVApp2/Views/Document/Index.cshtml
@model IEnumerable<CVApp2.Models.Document>

@section Scripts{


    <script>
        function Copypath(id, files) {

            var newid = "#tab" + id;
            var params = JSON.stringify({
                id: id,
                file: files
            });

            $.ajax({
                type: "POST",
                url: "/Document/Copypath",
                data: params,
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: OnSuccess1,
                failure: function (response) {
                    alert('Oops! something went wrong, failure: ' + response.d);
                },
                error: function (response) {
                    if (response.statusText == 'abort') {
                        return;
                    }
                    alert('Oops! something went wrong, error: ' + response);
                }
            });

        }

        function OnSuccess1(response) {
            var resumes = response;
            //alert("Kopied");
        }

    </script>

    }

<table class="table table-striped  table-hover tablesorter">
    <thead>
        <tr>
            <th>
                Group
            </th>
            <th>
                Document
            </th>
            <th>
                Tags
            </th>
            <th>
                Date Created
            </th>
            <th style="text-align:center;">
                Kopier
            </th>

            <th></th>
        </tr>


    </thead>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DocumentGroup.Name)
            </td>
            <td>
                <a href="/Document/ShowDocument?id=@item.Id&file=@item.ServerFileName" target="_blank">
                    @Html.DisplayFor(modelItem => item.FileName)
                </a>
            </td>


            <td>
                @Html.DisplayFor(modelItem => item.Tags)
            </td>
            <td width="125px">
                @item.Created.Date.ToShortDateString()
            </td>
            <td style="text-align:center;">
                <a class="templateLink" style="color:black;" href="/Document/copypath?id=@item.Id&file=@item.ServerFileName"><span class="glyphicon glyphicon-copy"></span> </a>
             
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                @Ajax.ActionLink("Delete", "Delete", "Document", new { id = item.Id }, new AjaxOptions { UpdateTargetId = "ajaxDialog", InsertionMode = InsertionMode.Replace, HttpMethod = "Get", OnSuccess = "showDialog" })
            </td>
        </tr>
    }

</table>