CVApp2/Models/DocumentGroup.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CVApp2.Models
{
    public class DocumentGroup : BaseEntity
    {
        [Required]
        [StringLength(50,ErrorMessage="Name cannot be longer than 50 characters")]
        public string Name { get; set; }

       [Column(TypeName = "varchar(MAX)")]
        public string Description { get; set; }

        public int ParentGroupId { get; set; }

    }
}

CVApp2/Controllers/DocumentGroupController.cs
using CVApp2.Models;
using CVApp2.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace CVApp2.Controllers
{
    public class DocumentGroupController : Controller
    {

         IDocumentGroupService _documentGroupService;
         IDocumentService _documentService;
         public DocumentGroupController()
        {
            _documentGroupService = new DocumentGroupService();
        }

        public ActionResult GroupTree()
        {
            var documentGroups = _documentGroupService.GetAll();
            return PartialView(documentGroups);
        }

        // GET: DocumentGroup
        public ActionResult Index()
        {
            var documentGroups = _documentGroupService.GetAll();
            return View(documentGroups);
        }

        // GET: DocumentGroup/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: DocumentGroup/Create
        public ActionResult Create()
        {
            DocumentGroup documentGroup = new DocumentGroup();
            return View(documentGroup);
        }

        // POST: DocumentGroup/Create
        [HttpPost]
        public ActionResult Create(DocumentGroup documentGroup)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    _documentGroupService.AddNew(documentGroup);
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(documentGroup);
                }

            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(documentGroup);
            }
        }

        // GET: DocumentGroup/Edit/5
        public ActionResult Edit(int id)
        {
            var documentGroup = _documentGroupService.GetDocumentGroupById(id);
            return View(documentGroup);
        }

        // POST: DocumentGroup/Edit/5
        [HttpPost]
        public ActionResult Edit(DocumentGroup documentGroup, FormCollection collection)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _documentGroupService.Update(documentGroup);
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(documentGroup);
                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(documentGroup);
            }
        }

        // GET: DocumentGroup/Delete/5

        public ActionResult Delete(int id)
        {
            DocumentGroup documentGroup = _documentGroupService.GetDocumentGroupById(id);
           
            return PartialView(documentGroup);
        }

        // POST: DocumentGroup/Delete/5
        [HttpPost]
        public ActionResult Delete(DocumentGroup documentGroup)
        {
            try
            {
                _documentGroupService.Delete(documentGroup);
                return Content("Deleted");
            }
            catch (Exception ex)
            {
                this.Response.StatusCode = 400;
                ModelState.AddModelError("", ex.Message);
                return PartialView(documentGroup);
            }
        }
    }
}

CVApp2/Views/DocumentGroup/Create.cshtml
@model CVApp2.Models.DocumentGroup

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_KnowledgeLayout.cshtml";

}

<div class="editContainerPanel restrictedHeight">

    <h3><span class="glyphicon glyphicon-plus"></span> Dokument Gruppe</h3>
    <hr />
    <div class="row">
        <div class="col-md-5 col-md-offset-1">


            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()


                <div class="EditPageSection bg-success">Gruppe Detaljer</div>

                <div class="form-horizontal">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.Label("Navn", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control"} })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Beskrivelse", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    @Html.HiddenFor(model => model.ParentGroupId, new { id = "parentGroupId" })

                    <div class="form-group">
                        @Html.Label("Overordnet gruppe", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="form-control" style="height:auto;">
                                @Html.Action("GroupTree", "DocumentGroup")
                            </div>
                        </div>
                    </div>

                    <hr />

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Gem" class="btn btn-success" />
                        </div>
                    </div>
                </div>
            }



        </div>
    </div>

</div>

@section scripts{
    <script>
        $(function () {
            $("#groupTree").jstree({
                "checkbox": { "three_state": false },
                "core": {
                    "multiple": false,
                    "themes": {
                        "variant": "large"
                    }
                },
                "plugins": ["wholerow", "checkbox"]
            })
            .on("changed.jstree",
     function (evt, data) {

         var i, j;
         $("#parentGroupId").val(0);
         for (i = 0, j = data.selected.length; i < j; i++) {
             var node_id = (data.instance.get_node(data.selected[i]).id);
             $("#parentGroupId").val(($("#" + node_id).attr("data-value")));

         }

         
     }
);


        });

    </script>
}

CVApp2/Views/DocumentGroup/Delete.cshtml
@model CVApp2.Models.DocumentGroup

@{
    ViewBag.Title = "Delete";
}
<div>
    @using (Ajax.BeginForm(new AjaxOptions { OnSuccess = "handleDeleteSuccess", OnFailure = "handleError" }))
    {
        @Html.AntiForgeryToken()
        <div class="">

            @Html.HiddenFor(model => model.Id)

            @Html.HiddenFor(model => model.Name)
            @Html.HiddenFor(model => model.Description)
            <div class="form-group">
                <div class="col-md-1">
                    <span style="font-size:32px;" class="text-danger glyphicon  glyphicon-question-sign"></span>
                </div>
                <div class="col-md-11">
                    <h4>Er du sikker på du vil slette dokumentet gruppe ? </h4>
                    <h4> @Html.ValueFor(model => model.Name)?</h4>
                    <br />

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <br />
                </div>
            </div>





            <div class="">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" value="Delete" class="btn btn-primary "><span class="glyphicon glyphicon-ok"></span> Ja </button>
                    <input type="button" value="Nej" class="btn btn-default" id="diagCloseBtn" onclick="closeDialog();" />
                </div>
            </div>
        </div>
    }
</div>

CVApp2/Views/DocumentGroup/Edit.cshtml
@model CVApp2.Models.DocumentGroup

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_KnowledgeLayout.cshtml";
    Html.EnableClientValidation(true);
}

<div class="editContainerPanel restrictedHeight">

    <h3><span class="glyphicon glyphicon-edit"></span> Rediger Dokument Gruppe</h3>
    <hr />
    <div class="row">
        <div class="col-md-5 col-md-offset-1">


            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()


                <div class="EditPageSection bg-success">Gruppe Detaljer</div>

                <div class="form-horizontal">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.Label("Navn", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Beskrivelse", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    @Html.HiddenFor(model => model.ParentGroupId, new { id = "parentGroupId" })

                    <div class="form-group">
                        @Html.Label("Overordnet gruppe", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="form-control" style="height:auto;">
                                @Html.Action("GroupTree", "DocumentGroup")
                            </div>
                        </div>
                    </div>

                    <hr />

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Gem" class="btn btn-success" />
                            @Html.ActionLink("Luk", "Index", null, new {@class="btn btn-default" })
                        </div>
                    </div>
                </div>
            }



        </div>
    </div>

</div>

@section scripts{
    <script>
    $(function () {
        $("#groupTree").on("ready.jstree", function (event, data) {

            data.instance.open_all();
            var requiredNode = $('#groupTree').find("li[data-value=@Model.ParentGroupId]").attr("id");
            data.instance.close_all();

            data.instance.open_node([requiredNode]);
            data.instance.select_node([requiredNode]);
            })
            .jstree({

                "checkbox": { "three_state": false },
                "core": {
                    "multiple": false,
                    "themes": {
                        "variant": "large"
                    }
                },
                "plugins": ["wholerow", "checkbox"]
            })

            .on("changed.jstree",
                function (evt, data) {

                    var i, j;
                    $("#parentGroupId").val(0);
                    for (i = 0, j = data.selected.length; i < j; i++) {
                        var node_id = (data.instance.get_node(data.selected[i]).id);
                        $("#parentGroupId").val(($("#" + node_id).attr("data-value")));

                    }


                });


    });

</script>
}

CVApp2/Views/DocumentGroup/GroupTree.cshtml
@model IEnumerable<CVApp2.Models.DocumentGroup>


<div id="groupTree">

        @PrintCategoryTree(Model.Where(x => x.ParentGroupId==0))
    
</div>

@functions{
    public IHtmlString PrintCategoryTree(IEnumerable<CVApp2.Models.DocumentGroup> levelCategories)
    {
        if (levelCategories.Count() == 0) { return new HtmlString(String.Empty); }

        System.Text.StringBuilder sb = new System.Text.StringBuilder();

        TagBuilder childBuilder = new TagBuilder("li");

        foreach (var item in levelCategories.OrderBy(x => x.Name))
        {
            childBuilder.Attributes.Clear();
            childBuilder.Attributes.Add("data-value", item.Id.ToString());
            var sub = PrintCategoryTree(Model.Where(x => x.ParentGroupId == item.Id));

            childBuilder.InnerHtml = item.Name + sub.ToString();
            sb.AppendLine(childBuilder.ToString());
        }

        TagBuilder tagBuilder = new TagBuilder("ul")
        {
            InnerHtml = sb.ToString()
        };

        return Html.Raw(tagBuilder.ToString());
    }
}

CVApp2/Views/DocumentGroup/Index.cshtml
@model IEnumerable<CVApp2.Models.DocumentGroup>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_KnowledgeLayout.cshtml";
}


<div class="editContainerPanel restrictedHeight">

    <h3> <span class="glyphicon glyphicon-grain"></span>  Dokument Gruppe</h3>
    <hr />

    <div class="row">
        <div class="col-md-3">
            <div class="input-group">

                <input type="text" class="form-control " id="searchGroupText" placeholder="Søg" />
                <span class="input-group-btn">
                    <button class="btn  btn-default" id="clearGroupText">
                        <i class="glyphicon glyphicon-remove"></i>
                    </button>
                </span>
            </div>
        </div>
        <div class="col-md-9">
            <div class="text-right">
                @Html.ActionLink("Tilføj Ny Gruppe", "Create", null, new { @class = "btn btn-success", style = "margin-bottom:10px;" })
            </div>
        </div>
    </div>

    <div class="form-control" style="height:auto;">
        <div id="groupTree">

            @PrintGroupTree(Model.Where(x => x.ParentGroupId == 0))

        </div>

    </div>
</div>

<div id="ajaxDialog" class="ajaxDialog" style="min-width:500px;"></div>


@functions{
    public IHtmlString PrintGroupTree(IEnumerable<CVApp2.Models.DocumentGroup> levelCategories)
    {
        if (levelCategories.Count() == 0) { return new HtmlString(String.Empty); }

        System.Text.StringBuilder sb = new System.Text.StringBuilder();

        TagBuilder childBuilder = new TagBuilder("li");

        foreach (var item in levelCategories.OrderBy(x => x.Name))
        {
            childBuilder.Attributes.Clear();
            childBuilder.Attributes.Add("data-value", item.Id.ToString());
            var sub = PrintGroupTree(Model.Where(x => x.ParentGroupId == item.Id));

            childBuilder.InnerHtml = string.Format("<table   style='display: inline-block'><tr><td><b>{0} </b> &nbsp; {1} &nbsp; <a href='{2}' class='btn btn-default btn-xs'>Rediger</a> {3} </td></tr></table>", item.Name, item.Description, Url.Action("Edit", new { id = item.Id }), Ajax.ActionLink("Slet", "Delete", new { id = item.Id }, new AjaxOptions { UpdateTargetId = "ajaxDialog", InsertionMode = InsertionMode.Replace, HttpMethod = "Get", OnSuccess = "showDialog" }, new { @class = "btn btn-default btn-xs" })) + sub.ToString();
            sb.AppendLine(childBuilder.ToString());

        }

        TagBuilder tagBuilder = new TagBuilder("ul")
        {
            InnerHtml = sb.ToString()
        };

        return Html.Raw(tagBuilder.ToString());
    }
}


@section scripts{
    <script>
        $(function () {

            to = false;
            $("#searchGroupText").on('input', OnSearchTextChange);


            $("#clearGroupText").click(function () {
                $("#searchGroupText").val("");
                OnSearchTextChange();
            });



            $("#ajaxDialog").dialog({ autoOpen: false, modal: true, closeText: "", hide: "fadeOut", title: "Knowledge Søg", width: "auto", position: { my: "center top", at: "center top+175", collision: "fit" } });


            $("#groupTree").jstree({
                "checkbox": { "three_state": false },
                "core": {
                    "html_titles" : true,
                    "multiple": false,
                    "themes": {
                        "variant": "large"
                    }
                },
                "plugins": ["wholerow","search"]
            })
            .on('ready.jstree', function () {
                $('#groupTree').off("click.jstree", ".jstree-anchor");
            })


        });


        function OnSearchTextChange() {

            if (to) { clearTimeout(to); }
            to = setTimeout(function () {
                var v = $('#searchGroupText').val();
                $('#groupTree').jstree(true).search(v);
            }, 250);

        }

        function showDialog(data) {
            $("#ajaxDialog").dialog("open");

        };

        function handleDeleteSuccess(data) {

            $("#ajaxDialog").dialog("close");
            location.href = "/DocumentGroup";
        };


        function handleError(ajaxContext) {

            $("#ajaxDialog").html(ajaxContext.responseText);
        };

        function closeDialog() {
            $("#ajaxDialog").dialog("close");
        };

    </script>
}